export enum ErrorCode {
    AUTH_INVALID_CREDENTIALS = 'AUTH_001',
    AUTH_TOKEN_EXPIRED = 'AUTH_002',
    AUTH_MISSING_REFRESH_TOKEN = 'AUTH_003',
    AUTH_INVALID_TOKEN = 'AUTH_004',

    VALIDATION_INVALID_INPUT = 'VALIDATION_001',
    VALIDATION_EAN_INVALID = 'VALIDATION_002',

    NOT_FOUND = 'NOT_FOUND_001',
    PRODUCT_NOT_FOUND = 'PRODUCT_001',
    PRODUCT_DUPLICATE = 'PRODUCT_002',

    DB_DUPLICATE_KEY = 'DB_002',
    DB_VALIDATION_ERROR = 'DB_003',

    INTERNAL_ERROR = 'INTERNAL_001',
}
